server:
  port: 8000
  servlet:
    context-path: /dbcheck
spring:
  application:
    name: DataCheck
  thymeleaf:
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /static/css/**,/static/js/**,/static/img/**